### ISSUE TITLE
Investigate core technologies

### ISSUE THREAD

**Issue by Kuzko02801** [Arquisoft/dede_en1a#1]
In order to work efficiently later on, we need to have a grasp of the technologies we will be using.

- [ReactJS](https://reactjs.org/tutorial/tutorial.html)
- [Typescript](https://www.typescriptlang.org/docs/handbook/intro.html)
- [Nodejs](https://nodejs.dev/learn)

**Comment by uo277963** [comment]
These are the resources I found for [MongoDB](https://www.javatpoint.com/mongodb-tutorial) and [Markdown](https://www.markdownguide.org/getting-started/)

**Comment by rosagarlo** [comment]
To start learning react I followed the tutorial and I really recommend it if you have not done it yet. You learn how to use the library by creating a tic tac toe simple game.
Here is the tutorial: https://reactjs.org/tutorial/tutorial.html#overview
Here is the plain code: https://codepen.io/gaearon/pen/oWWQNa?editors=0010

**Comment by ludvij** [comment]
I've found this video that could be helpful:
https://www.youtube.com/watch?v=FJDVKeh7RJI

**Comment by Kuzko02801** [comment]
This guide can help us understand the interaction between TypeScript and MongoDB.
[https://www.mongodb.com/compatibility/using-typescript-with-mongodb-tutorial](url)

**Comment by Elias-Llera** [comment]
If you are using intellij idea as an IDE, chech the AsciiDoc plugin to work with the documentation and visualize the end result whiel edditing the files. https://asciidoctor.org/docs/what-is-asciidoc/

**Comment by Kuzko02801** [comment]
This resource I found could be useful when developing the REST API.
https://medium.com/swlh/build-a-rest-api-with-express-js-and-typescript-dc2c8da89c52

**Comment by rosagarlo** [comment]
I found another React tutorial, where everything is categorized so we can learn or improve determined things:
https://www.w3schools.com/REACT/default.asp

**Comment by uo277963** [comment]
Not a core technology per se, but we can use the OSM Nominatim API to get coordinates. [Example](https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue,+birmingham&format=json&addressdetails=1).

**Comment by rosagarlo** [comment]
Here is a page with some react templates that could be useful: https://mui.com/getting-started/templates/#main-content
