### ISSUE TITLE
Checkout flow Redirect

### ISSUE THREAD

**Issue by uo277963** [Arquisoft/dede_en1a#113]
The checkout process will be reworked, in order to make it more consistent and on a step-by-step basis.

**Comment by Kuzko02801** [comment]
ORDER PROCESS

- CURRENT ONE -
- 
- User logs in (assumes it has a pod)
- App allows him to chekout (assumes it has products)
- App assumes it has a name and an address

- NEW ONE -

1 - The log in button goes to a new page
which asks the user to select a pod provider
and then redirects him to its log in web page.

In case the user has no pod, a sign up option will be used.
the token will be saved along its cart.

And when the user finished singning up a pod (or logging in), will
be redirected an have his cart restored.

2 - When the user has logged in or registered
he will be able to proceed to checkout. He will be
displayed the products he has bought and will be able
to modify his order. (A button to "Continue shopping should
be displayed too")

3 - When the user continues, he is displayed with his contact data
consisting of his name and address. In case he has no address or name
one should be provided.

4 - The order summary will be displayed and a button to go back to
the home page will be displayed.

**Comment by Kuzko02801** [comment]
The sign up page is done, the user now will be displayed an option in the navbar (when they are not logged in) which will redirect them to a page where they can choose the pod provider they want to sign up with.
