### ISSUE TITLE
[Delivery 3] Contributions - Luis Vijande

### ISSUE THREAD

**Issue by ludvij** [Arquisoft/dede_en1a#116]
My contributions for delivery 3 aree:
 - Fixing bugs #101 #104
 - cleaning dependencies tree #97 
 - Changing some of the components styling #109 
 - Adding a failsafe for the geocoder #104 
 - Fixing naming errors in the restapi

**Comment by pglez82** [comment]
Put your name in the title in the issue. Also, add links to pull requests and issues in which you contributed.

Thanks, Pablo
