### ISSUE TITLE
the inrupt solid-client-authn library is broken and should not be used

### ISSUE THREAD

**Issue by ludvij** [Arquisoft/dede_en1a#141]
After some really long hours of scratching my head wondering why our implementation was giving problemas i came across this thread
https://forum.solidproject.org/t/local-first-offline-and-solid-login/4896
in this thread it is said that the logout call only logs out from the app, but not the idp, making it impossible to change webId when login in again.

**Comment by ludvij** [comment]
must be noted, that now we are using solid ui which works fine to do the solid stuff, but, I think it might be good to move it to the backend and help with authorization since for some reason jwt does not work with react (?)

**Comment by pglez82** [comment]
So mean that after login out, if you login in again it will log with the same solid account without asking you for your credentials, not allowing to change the solid pod. is that correct?

**Comment by ludvij** [comment]
yes

**Comment by ludvij** [comment]
if you cahnge idp you can change credentials for the first time agian, but you can't change account in the same idp

**Comment by ludvij** [comment]
the plan was to move solid authentication to the backend to make authorization easier, since the library is buggy I think we won't change it ans come up with another solution.
Our current solution uses the react sdk and I think it has the same bug, but I might be mistaken

**Comment by ludvij** [comment]
Other solution could be to use the solid-auth-clien library, but I think it is deprecated

**Comment by ludvij** [comment]
But i guess i'm going to just try to make work jwt in the frontend or something like that to make authorization and not change solid

**Comment by pglez82** [comment]
I think this should be a group decision. If it works know and the thing that is not working is logging out, at least, that is working. Changing that part you take the risk on not getting on time and messing the project. Time to make some important decisions.
