### ISSUE TITLE
Time to have the app working

### ISSUE THREAD

**Issue by pglez82** [Arquisoft/dede_en1a#152]
I have been checking the deployments of the applications and I can see that yours if failing. This issue is just to remind you all that one day from the presentation you should have the software running and deployed. 

Also I can see that you have recent open issues with new functionality. It is good to keep improving the app but be careful with this because presentation day is very near and making big changes now can be risky. 

Remember to put a link also to the deployed application in main page of the repository.

**Comment by ludvij** [comment]
Apparently solid only works from https
and our deployment is only http
is that true?

**Comment by uo277963** [comment]
Everything is working now, I'm closing this to keep the issues tab clean.
