### ISSUE TITLE
First version of documentation review

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/dede_en1a#20]
Needed updates in documentation:

 - Go deeper in requirements overview
 - Add secondary qualitity attributes
 - Update constraints: add continuous integration to technical constraints and specify deadlines inorganizational constraints.
 - Add maps/delivery api to the context overview
 - Solution strategy -> add typecrypt  to react, specify the way to access to mongodb (like mongoose)
 - Typo in section 5, last part (databse)
 - Delete JDK from deplyment view

**Comment by ludvij** [comment]
I deleted the jdk from deployment and fixed some typos, I'll create a new branch for this

**Comment by ludvij** [comment]
Branch created is dev-docs-hotifx

**Comment by ludvij** [comment]
the branch is [dev-docs-hotifx](https://github.com/Arquisoft/dede_en1a/tree/dev-docs-hotfix)

**Comment by uo277963** [comment]
Closing this as the first docs version is long done.
