### ISSUE TITLE
Seller CRUD

### ISSUE THREAD

**Issue by Kuzko02801** [Arquisoft/dede_en1a#34]
Im assigned to develop the seller CRUD.

**Comment by Kuzko02801** [comment]
Implemented a basic REST API for Sellers, tomorrow I will test it works as expected. The material I used to develop it is the following:

- [https://rahmanfadhil.com/express-rest-api/](url)

**Comment by Kuzko02801** [comment]
Tried doing some testing and it partially worked, successfully connected to the database and retrieved the sellers (its empty) althoug I have been having problems with imports and exports. I will resume the testing tomorrow.

**Comment by uo277963** [comment]
For the sake of clarity, maybe we should try grouping the whole interface into the original api.ts class, instead of creating a new api for every entity.

**Comment by Kuzko02801** [comment]
I guess one approach would be to separate each REST in different .ts files and create a new file containing a router, export it and use it on said rest .ts files.

**Comment by Kuzko02801** [comment]
Managed to implement a rest api for Seller.
#35

**Comment by Kuzko02801** [comment]
@uo277963 Exactly, thats what I did.

**Comment by ludvij** [comment]
since we ar egoing to have a ton of differnet calls to teh api in api.ts I think we should create a router for product seller and order like I did in backaned-product-CRUD

**Comment by ludvij** [comment]
or maybe just joins the controller and the router into one class
